# -*- coding: utf-8 -*-
"""common_client.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xa1qkgnyzwQ8oP5nTgbn4c46pMfKEjiP
"""

class CommonClient:
    def execute(self, ability_name, state):
        print(f"[COMMON] Executing {ability_name}")
        # Mock logic: just update state
        state.update(ability_name, f"result_of_{ability_name}")
        return state