# -*- coding: utf-8 -*-
"""state.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xa1qkgnyzwQ8oP5nTgbn4c46pMfKEjiP
"""

class State:
    def __init__(self, initial_payload=None):
        self.data = initial_payload or {}

    def update(self, key, value):
        self.data[key] = value

    def get(self, key, default=None):
        return self.data.get(key, default)

    def __str__(self):
        return str(self.data)